S = GameTree+
GameTree   = '(' Node+ GameTree*  Newline? ')' Newline?
Node = Newline? ';' Property*
Property = UpperLetter UpperLetter? PropValue+
PropValue  = ( '[' CValueType ']' )  Newline?
CValueType = (ValueType | Compose)
Compose    = ValueType ':' ValueType
+ValueType  = ( Text )?
Newline = #'\n'
Text = Letter+
Digit = ('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9')
Digits = Digit+
Number = ('+' '-')? Digits
Compose    = ValueType ':' ValueType
UpperLetter = #'[A-Z]'
LowerLetter = #'[a-z]'
Letter = UpperLetter | LowerLetter

