S = GameTree+
GameTree   = Newline* '(' Sequence GameTree* ')' Newline*
Sequence   = Node+
Node       = <';'> Data* Newline*
Data   = (PropIdent PropValue+) | Move
Move       = ('B' | 'W') <'['> #"[a-s]" #"[a-s]" <']'>
<PropIdent>  = UcLetter+
<PropValue>  = '[' CValueType ']' Newline*
<CValueType> = (ValueType | Compose)
<ValueType>  = (None | Text)
<UcLetter>   = #'[A-Z]'
Compose    = ValueType ':' ValueType
None       = ''
Space      = ' '
<Newline>    = <#"\n"> | <#"\r"> | <#"\r\n">
EscapedNewline = #"\\\n"
Digit      = #"\d"
Number = ('-' | '+')? Digit+
<Text> = SimpleText
<SimpleText> = ( #"[^\]:]" )+
