S = GameTree+
GameTree   = '(' Node+ GameTree*  Newline? ')' Newline?
Move = ('W' | 'B') '[' #\"[a-z]{2}\" ']'
Node       = Newline? ';' ( Property* | Move )
Property   =  #\"[A-Z]{1,2}\" PropValue+
PropIdent  = #\"[A-Z]{1,2}\"
PropValue  = ( '[' CValueType ']' )  Newline?
CValueType = (ValueType | Compose)
Newline = #\"\n\"
Digit = ('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9')
Digits = Digit+
Number = ('+' '-')? Digits
Real = Number '.' Digits
Double = Real 'e' Real
Color = 'white' 'black'
Text = ( #\"(\\w|\\d)+\" | '-' | '.' | ' ' |'+'|'='|':'  | Newline )+
Point = (LcLetter LcLetter)
ValueType  = ( Number | Real | Double | Color | Text )?
LcLetter = #\"[a-z]\"
UcLetter   = #\"[A-Z]\"
Compose    = ValueType ':' ValueType
